[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.0" # Ruff version.
hooks = [
  # Run the linter.
  { id = "ruff-check", args = ["--fix"], types_or = ["python", "pyi"] },

  # Run the formatter.
  { id = "ruff-format", types_or = ["python", "pyi"] },
]

[[repos]]
repo = "https://github.com/facebook/pyrefly-pre-commit"
rev = "0.61.0" # Pyrefly pre-commit hook version.
hooks = [
  {
    id = "pyrefly-check",
    pass_filenames = false,
    additional_dependencies = [
      "beautifulsoup4>=4",
      "requests>=2",
      "polars>=1",
      "pytest>=9",
      "flaky>=3",
    ] },
]